plugins {
    id 'java'
}

group = 'com.easytrading'
version = rootProject.version

base {
    archivesName = 'EasyTrading-Russificator'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    compileOnly project(':')
    compileOnly 'org.spigotmc:spigot-api:1.21.1-R0.1-SNAPSHOT'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}
